// swift-tools-version:5.9
// Generated by DAKA's scripts/release_photoeditkit_package.sh. Edit the script,
// not this file.
import PackageDescription

let package = Package(
    name: "PhotoEditKit",
    platforms: [.iOS("17.6")],
    products: [
        .library(name: "PhotoEditKit", targets: ["PhotoEditKit"])
    ],
    targets: [
        .binaryTarget(
            name: "PhotoEditKit",
            url: "https://github.com/8kdesign/PhotoEditKit/releases/download/1.0.2/PhotoEditKit.xcframework.zip",
            checksum: "e8605601d96abb73db0f84b97f3c05bc413de08cf3afd8f2d19ea7a414bdbbd5"
        )
    ]
)
