// swift-tools-version:5.9
// Generated by DAKA's scripts/release_photoeditkit_package.sh. Edit the script,
// not this file.
import PackageDescription

let package = Package(
    name: "PhotoEditKit",
    platforms: [.iOS("17.6")],
    products: [
        .library(name: "PhotoEditKit", targets: ["PhotoEditKit"])
    ],
    targets: [
        .binaryTarget(
            name: "PhotoEditKit",
            url: "https://github.com/8kdesign/PhotoEditKit/releases/download/1.0.6/PhotoEditKit.xcframework.zip",
            checksum: "262e76f320ce1d850c65c9368dc2ceaa3ce08ba9ccfd8e03b676499e3ac50af3"
        )
    ]
)
